[package]
name = "collectibleswap"
version = "0.1.0"
license = "MIT"

[addresses]
collectibleswap ="0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
emergency_admin ="0x0831c065f08f654d912a39f5cd0ee6bb5288d902c3d8fbfcc61021106fa12e22"
liquidity_account="0x385068db10693e06512ed54b1e6e8f1fb9945bb7a78c28a45585939ce953f99e"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"
test_lp_owner = "0x13"
test_token_creator = "0x14"
test_asset_recipient = "0x15"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v0.3.5" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="aptos-cli-v0.3.5" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="aptos-cli-v0.3.5" }

[dependencies.CollectibleSwapLP]
local = "./liquidity_coin/"

