[package]
name = "collectibleswap"
version = "0.1.0"
license = "MIT"

[addresses]
collectibleswap ="0x0831c065f08f654d912a39f5cd0ee6bb5288d902c3d8fbfcc61021106fa12e22"
emergency_admin ="0x0831c065f08f654d912a39f5cd0ee6bb5288d902c3d8fbfcc61021106fa12e22"
liquidity_account="0xe4333845fd36cb82ed7ab2f95c0276368aa3f8fa5b53346c8d891effb6d97fe2"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"
test_lp_owner = "0x13"
test_token_creator = "0x14"
test_asset_recipient = "0x15"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v0.3.5" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="aptos-cli-v0.3.5" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="aptos-cli-v0.3.5" }

[dependencies.CollectibleSwapLP]
local = "./liquidity_coin/"

