[package]
name = "collectibleswap-0.1.0"
version = "0.1.0"
license = "MIT"
upgrade_policy = "compatible"

[addresses]
collectibleswap ="0xd39111acba9f96a14150674b359d564e566f8057143a0593723fe753fc67c3b2"
emergency_admin ="0xd39111acba9f96a14150674b359d564e566f8057143a0593723fe753fc67c3b2"
liquidity_account="0x5c6ef5b5664d49e24752d2a60cce65fad9d1a9b9b23af05ed0ba668caa7efcc0"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"
test_lp_owner = "0x13"
test_token_creator = "0x14"
test_asset_recipient = "0x15"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v0.3.9" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="aptos-cli-v0.3.9" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-token/", rev="aptos-cli-v0.3.9" }

[dependencies.CollectibleSwapLP]
local = "./liquidity_coin/"

[dependencies.CollectibleSwapInit]
local = "./collectibleswap_init/"

