[package]
name = 'CollectibleSwapLP'
version = '1.0.0'

[addresses]
liquidity_account = "0x60c41ec970fe1efec0aae3a0774137d95675049c7928a4483d50454a107319eb"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-stdlib/", rev="aptos-cli-v0.3.5" }
